### ISSUE TITLE
BOOSTER overlays went funny after Gareth buying boosters

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#123]
Gaz bought a booster far right and then 2nd to right which then caused the attached image

**Comment by Rich-Option4Studios** [comment]
![image](https://cloud.githubusercontent.com/assets/11824245/9154668/0bd68822-3e94-11e5-8a70-ba35c23fd93b.jpg)

**Comment by Option4Studios** [comment]
check if [#127] has fixed this issue - i believe this is when a marker was selected whilst selecting something on booster overlay - [#127] would stop this occuring
