### ISSUE TITLE
GAMEPLAY you can swap robots you shouldn't be able to

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#125]

**Comment by Rich-Option4Studios** [comment]
So far I can only recreate with the robots at the edge of the grid (on iPad) and I can't see an obvious reason why it's only sometimes.

Suggestion: Rich to try and recreate in Unity Editor. We could do with a set of debug logs to output what what logic is occurring when a robot is moved.

**Comment by Rich-Option4Studios** [comment]
![file 11-08-2015 15 36 12](https://cloud.githubusercontent.com/assets/11824245/9201075/094ef9ee-4043-11e5-999e-08274bf779b5.jpeg)
![file 11-08-2015 15 35 06](https://cloud.githubusercontent.com/assets/11824245/9201076/095729b6-4043-11e5-9abb-a4369271927b.jpeg)
![file 11-08-2015 15 34 41](https://cloud.githubusercontent.com/assets/11824245/9201077/095848aa-4043-11e5-8f6d-736690b73d0a.jpeg)
