### ISSUE TITLE
OVERLAY: Duplicate SmoothMoves Robots (minor)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#126]
I can't recreate yet, I was messing around repeatedly buying boosters, closing the window and selecting the same level.

Might be worth checking if there is a logical explanation why the same smooth moves robots can instantiate on top of each other

**Comment by Rich-Option4Studios** [comment]
![file 11-08-2015 15 34 03](https://cloud.githubusercontent.com/assets/11824245/9200597/7db718fa-4040-11e5-9a3f-d9a375a06c72.png)

You will need to look closely, but there are two pink robots showing

**Comment by Option4Studios** [comment]
Need to set difference between menu start overlay and robot goals in level

**Comment by Option4Studios** [comment]
fixed
