### ISSUE TITLE
LEVEL MENU: Couldn't buy more lives when lives zero

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#143]

**Comment by Rich-Option4Studios** [comment]
![capture1](https://cloud.githubusercontent.com/assets/11824245/9860894/bc4fc930-5b26-11e5-8687-25e3ebb50eeb.JPG)

**Comment by Rich-Option4Studios** [comment]
![capture2](https://cloud.githubusercontent.com/assets/11824245/9860902/c79fda3c-5b26-11e5-92b3-ec1db34c7517.JPG)
