### ISSUE TITLE
MENU: Tidy top bar

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/RobotsGoHome#18]
Tidy up top bar on the menu, consistent positioning of plus signs and move money closer to text box

![image](https://cloud.githubusercontent.com/assets/11822462/7076975/1e198370-df05-11e4-8c78-1b77ef7f9951.png)

**Comment by Option4Studios** [comment]
![hyw_new2-02](https://cloud.githubusercontent.com/assets/11822462/7076121/1271a684-deff-11e4-94a3-60fb3fde99e3.png)

Just a test uploading an image via github
