### ISSUE TITLE
LOCALISATION: complete font sets

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/RobotsGoHome#22]
Complete 2Dtextmesh pro font including all European characters. Also check text mesh pro. May have to revert to a common font for other languages

- [x] item 1
- [ ] item 2
- [ ] item 3

**Comment by Option4Studios** [comment]
[ ] item 1
[ ] item 2

**Comment by Rich-Option4Studios** [comment]
May be missing from commits - Char Pad X needs to be -8
