### ISSUE TITLE
OVERLAYS: Black overlay is not long enough on Hudl 2 & Android phone

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#38]

**Comment by Rich-Option4Studios** [comment]
I've seen on a few devices such as the Android phone when black overlays don't cover entire background. Consider making height extra long and perhaps a bit of width for good measure

**Comment by Option4Studios** [comment]
OK Hudl2, on Android and iphone 5

**Comment by Rich-Option4Studios** [comment]
![image](https://cloud.githubusercontent.com/assets/11824245/7460439/f5d6d88c-f29a-11e4-8560-0fd9ac70a8f0.jpg)

On my iPhone 5
