### ISSUE TITLE
OVERLAYS: animate all elements in...

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/RobotsGoHome#40]

**Comment by Option4Studios** [comment]
Already on end of level overlay.
Need to add to:
-[ ] start level overlay
-[ ] iap overlays

**Comment by Option4Studios** [comment]
Need to make the robot goals be on top of the fade, or the batteries be beneath...

**Comment by Option4Studios** [comment]
I've made the menu and level main UI disappear when an overlay is showing - and show it again when it's shut
