### ISSUE TITLE
LEVEL: Conflict of bars

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#52]
In some scenarios a title bar can visually conflict with a bar underneath. An example is shown in the comments where the menu button is peaking out underneath. Perhaps we fade the level game bar to 50%

**Comment by Rich-Option4Studios** [comment]
![img_0063](https://cloud.githubusercontent.com/assets/11824245/7282051/4e867dea-e925-11e4-9839-db6b7c8ea0fd.PNG)

**Comment by Option4Studios** [comment]
This has been fixed with issue [#40]
