### ISSUE TITLE
SAVING: Losing save data?

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#54]
I am sure I've done a few levels on the ipad, removed RGH a few times from the multitasking list and ended up starting the tutorial again and all saved data gone!

We probably need some visual debug data on the ipad like a message saying it can't find the save file or can't load a piece of data.

**Comment by Rich-Option4Studios** [comment]
I tried again, removed it once and it was fie - all save data restored. Removed it again and had to start on the tutorial

**Comment by Rich-Option4Studios** [comment]
New strategy of saving  2 files required. Main save  file for when changing scenes, completing levels and OnPause. Second save file when doing OnApplicationQuit.

Issue opened with EasySave developer:

http://www.moodkie.com/forum/viewtopic.php?f=5&t=787&p=1929#p1929

Maybe Unity 5 bug.
