### ISSUE TITLE
IAP: Buttons  disappear on full lives panel. May have been linked to disabled colour

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#63]
![capture](https://cloud.githubusercontent.com/assets/11824245/7436242/74f9a7b6-f043-11e4-829b-c0eb5231b6ec.JPG)

**Comment by Option4Studios** [comment]
Remove buttons entirely when lives are full

**Comment by Option4Studios** [comment]
This was due to me setting the sprites as blank - forgetting about/was before we added the localised dynamic text! doh!

Have now hidden the button when not needed I.e. lives full
