### ISSUE TITLE
Clash between end of game overlays and level up 

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/RobotsGoHome#78]
On the 4th level I don't know if the level ended but the end of level panel came up just as the ufo came in. Might be coincidence, however the level seemed to continue playing for a tiny bit longer. See screenshot

**Comment by Rich-Option4Studios** [comment]
![image](https://cloud.githubusercontent.com/assets/11824245/7978628/638ef362-0a8f-11e5-9782-bbf1ec388b6c.jpg)

**Comment by Option4Studios** [comment]
Cancel the coroutine of special characters if less than 10 seconds left - reactivate if add more time?!
