### ISSUE TITLE
BUTTONS: when pulsating and select them, animation = 'thuds'

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/RobotsGoHome#90]

**Comment by Option4Studios** [comment]
Have changed start screen to use Dotween component and remove over and out method calls...

**Comment by Option4Studios** [comment]
add to energize when active?

**Comment by Option4Studios** [comment]
Have changed start screen, settings scene and start overlay

**Comment by Option4Studios** [comment]
need to change:
[] - buy a life: add lives button
[] - buy booster: buy button
[] - end level overlay: next and connect buttons
